/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

/**
 *
 * @author Hugo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btmCadF = new javax.swing.JButton();
        btmCadC = new javax.swing.JButton();
        btmLisF = new javax.swing.JButton();
        btmLisC = new javax.swing.JButton();
        btmLog = new javax.swing.JButton();
        btmCai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));

        btmCadF.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btmCadF.setText("Cadastrar funcionario");
        btmCadF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmCadFActionPerformed(evt);
            }
        });

        btmCadC.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btmCadC.setText("Cadastrar cliente");
        btmCadC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmCadCActionPerformed(evt);
            }
        });

        btmLisF.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btmLisF.setText("Lista de funcionarios");
        btmLisF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmLisFActionPerformed(evt);
            }
        });

        btmLisC.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btmLisC.setText("Lista de clientes");
        btmLisC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmLisCActionPerformed(evt);
            }
        });

        btmLog.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btmLog.setText("Login");
        btmLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmLogActionPerformed(evt);
            }
        });

        btmCai.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btmCai.setText("Caixa");
        btmCai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmCaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btmCai, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmCadC, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmCadF, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmLisF, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmLisC, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmLog, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btmCai)
                .addGap(18, 18, 18)
                .addComponent(btmCadF)
                .addGap(18, 18, 18)
                .addComponent(btmCadC)
                .addGap(18, 18, 18)
                .addComponent(btmLisF)
                .addGap(18, 18, 18)
                .addComponent(btmLisC)
                .addGap(18, 18, 18)
                .addComponent(btmLog)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmCaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmCaiActionPerformed
        dispose();
        Caixa CX = new Caixa();
        CX.setVisible(true);
    }//GEN-LAST:event_btmCaiActionPerformed

    private void btmCadFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmCadFActionPerformed
        dispose();
        CadastrarFuncionario CF = new CadastrarFuncionario();
        CF.setVisible(true);
    }//GEN-LAST:event_btmCadFActionPerformed

    private void btmCadCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmCadCActionPerformed
        dispose();
        CadastrarCliente CC = new CadastrarCliente();
        CC.setVisible(true);
    }//GEN-LAST:event_btmCadCActionPerformed

    private void btmLisFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmLisFActionPerformed
        dispose();
        ListaFuncionario LF = new ListaFuncionario();
        LF.setVisible(true);
    }//GEN-LAST:event_btmLisFActionPerformed

    private void btmLisCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmLisCActionPerformed
        dispose();
        ListaClientes LC = new ListaClientes();
        LC.setVisible(true);
    }//GEN-LAST:event_btmLisCActionPerformed

    private void btmLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmLogActionPerformed
        dispose();
        Login L = new Login();
        L.setVisible(true);
    }//GEN-LAST:event_btmLogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmCadC;
    private javax.swing.JButton btmCadF;
    private javax.swing.JButton btmCai;
    private javax.swing.JButton btmLisC;
    private javax.swing.JButton btmLisF;
    private javax.swing.JButton btmLog;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
